language: python

before-install:
  - pip install -r requirements.txt

script:
  - python manage.py migrate
  - black .
  - flake8 . --max-line-length=88
  - coverage run --source='.' manage.py test

after_success:
  - coveralls